### ISSUE TITLE
Node module id mentioned in the doc is incorrect 

### ISSUE THREAD

**Issue by kaviththiranga** [asgardeo/asgardeo-auth-node-sdk#20]
**Is your suggestion related to a missing or misleading document? Please describe.**
``` npm install @asgardeo/auth-nodejs-sdk ``` should be corrected as ```npm install @asgardeo/auth-node```

**Describe the improvement**

---

### Optional Fields

**Additional context**

**Related Issues:**

**Comment by rajithacharith** [comment]
Closing the issue since this is fixed with https://github.com/asgardeo/asgardeo-auth-node-sdk/pull/22
